---

resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"


default_container: "docker://hydragenetics/common:0.0.1"


reference:
  fasta: "/data/ref_genomes/GRCh38/broad/Homo_sapiens_assembly38.fasta"
  1000Ginterval: "/projects/wp3/nobackup/Workspace/PEDDY/1000G.bed"
  design_intervals: "/projects/wp3/Reference_files/Manifest/Clinical_research_exome/TWIST/Twist_Exome_Target_hg19_interval_list.bed"
  design_bed: "/projects/wp3/Reference_files/Manifest/Clinical_research_exome/TWIST/Twist_Exome_Target_hg19.bed"

#Tror inte dessa behövs i min config, det hämtas ju i modulerna
trimmer_software: "fastp"

fastp_pe:
  container: "docker://hydragenetics/fastp:0.20.1"

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"

# tools:
#   bamutil: "docker://marrip/bamutil:v1.0.14"
#   python: "docker://python:3.9.1-slim-buster"
#   r: "docker://marrip/r-base:4.0.3"
#   ubuntu: "docker://ubuntu:18.04"
