---

resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"


default_container: "docker://hydragenetics/common:0.0.1"


reference:
  fasta: "/data/ref_genomes/GRCh38/broad/Homo_sapiens_assembly38.fasta"
#  1000Ginterval: "/projects/wp3/nobackup/Workspace/PEDDY/1000G.bed"
  design_intervals: "/projects/wp3/Reference_files/Manifest/Clinical_research_exome/TWIST/Twist_Exome_Target_hg19_interval_list.bed"


programdir:
  dir: "/projects/wp3/nobackup/Workspace/WGS_pipeline_GPU_test/Poirot_RD-WGS/workflow"

genepanels:
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/ALS.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/Aortopatier.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/Arytmier.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/Bindvav.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/BRCA.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/CADASIL.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/EBS.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/EDS.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/epilepsi.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/HHT.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/Ichtyos.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/kardio.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/Kraniosynostos_v2.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/neuromuskular.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/neuropati.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/Periodisk_paralys.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/Rasopatier.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/Sotos.bed
  - /projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/Trombocytopenier.bed

mosdepth:
  container: "docker://hydragenetics/mosdepth:0.3.2"

#Tror inte dessa behövs i min config, det hämtas ju i modulerna
trimmer_software: "fastp"

fastp_pe:
  container: "docker://hydragenetics/fastp:0.20.1"

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"

# tools:
#   bamutil: "docker://marrip/bamutil:v1.0.14"
#   python: "docker://python:3.9.1-slim-buster"
#   r: "docker://marrip/r-base:4.0.3"
#   ubuntu: "docker://ubuntu:18.04"
